const currencyOptions = [
    { value: 'usd', label: '🇺🇸 USD - United States Dollar' },
    { value: 'gbp', label: '🇬🇧 GBP - British Pound' },
    { value: 'aud', label: '🇦🇺 AUD - Australian Dollar' },
    { value: 'jpy', label: '🇯🇵 JPY - Japanese Yen' },
    { value: 'bgn', label: '🇧🇬 BGN - Bulgarian Lev' },
    { value: 'czk', label: '🇨🇿 CZK - Czech Koruna' },
    { value: 'dkk', label: '🇩🇰 DKK - Danish Krone' },
    { value: 'huf', label: '🇭🇺 HUF - Hungarian Forint' },
    { value: 'pln', label: '🇵🇱 PLN - Polish Zloty' },
    { value: 'ron', label: '🇷🇴 RON - Romanian Leu' },
    { value: 'sek', label: '🇸🇪 SEK - Swedish Krona' },
    { value: 'chf', label: '🇨🇭 CHF - Swiss Franc' },
    { value: 'isk', label: '🇮🇸 ISK - Icelandic Krona' },
    { value: 'nok', label: '🇳🇴 NOK - Norwegian Krone' },
    { value: 'try', label: '🇹🇷 TRY - Turkish Lira' },
    { value: 'brl', label: '🇧🇷 BRL - Brazilian Real' },
    { value: 'cad', label: '🇨🇦 CAD - Canadian Dollar' },
    { value: 'cny', label: '🇨🇳 CNY - Chinese Yuan' },
    { value: 'hkd', label: '🇭🇰 HKD - Hong Kong Dollar' },
    { value: 'idr', label: '🇮🇩 IDR - Indonesian Rupiah' },
    { value: 'ils', label: '🇮🇱 ILS - Israeli Shekel' },
    { value: 'inr', label: '🇮🇳 INR - Indian Rupee' },
    { value: 'krw', label: '🇰🇷 KRW - South Korean Won' },
    { value: 'mxn', label: '🇲🇽 MXN - Mexican Peso' },
    { value: 'myr', label: '🇲🇾 MYR - Malaysian Ringgit' },
    { value: 'nzd', label: '🇳🇿 NZD - New Zealand Dollar' },
    { value: 'php', label: '🇵🇭 PHP - Philippine Peso' },
    { value: 'sgd', label: '🇸🇬 SGD - Singapore Dollar' },
    { value: 'thb', label: '🇹🇭 THB - Thai Baht' },
    { value: 'zar', label: '🇿🇦 ZAR - South African Rand' },
  ];
  
  export default currencyOptions;
  