name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  backend-tests:
    runs-on: self-hosted
    name: Run Backend Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          cd back
          npm install

      # - name: Check MySQL Connection
      #   run: |
      #     mysql -usammy -pasdf
      #     exit

      - name: Run tests
        env:
          DATABASE_HOST: localhost          # Points to your server's MySQL instance
          DATABASE_PORT: 3306               # MySQL's default port
          DATABASE_USERNAME: sammy       # Replace with the actual MySQL username
          DATABASE_PASSWORD: asdf  # Replace with the actual MySQL password
          DATABASE_NAME: currencies       # Replace with the name of the database for testing
        run: |
          cd back
          npm install mysql --save
          npm run test


  # frontend-tests:
  #   runs-on: self-hosted
  #   name: Run Frontend Tests
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '22'

  #     - name: Install dependencies
  #       run: |
  #         cd front
  #         npm install

  #     - name: Run tests
  #       run: |
  #         cd front
  #         npm test

  # deploy:
  #   runs-on: ubuntu-24.01
  #   needs: [
  #     backend-tests,
  #     # frontend-tests
  #     ]

    # name: Deploy Application
    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v2

    #   - name: Set up SSH
    #     uses: webfactory/ssh-agent@v0.5.3
    #     with:
    #       ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    #   - name: Deploy Backend
    #     run: |
    #       ssh root@134.209.252.76 "cd /var/www/currency/back && git pull && npm install && npm run build && pm2 restart back"

    #   - name: Deploy Frontend
    #     run: |
    #       ssh root@134.209.252.76 "cd /var/www/currency/front && git pull && npm install && npm run build && pm2 restart front"

    #   - name: Rollback on Failure
    #     if: failure()
    #     run: |
    #       ssh root@134.209.252.76 "cd /var/www/currency/back && git reset --hard HEAD~1 && pm2 restart back"
    #       ssh root@134.209.252.76 "cd /var/www/currency/front && git reset --hard HEAD~1 && pm2 restart front"
