name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  backend-tests:
    runs-on: self-hosted
    name: Run Backend Tests
    services:
      mysql:
        image: mysql:8.0.39
        env:
          MYSQL_ROOT_PASSWORD: asdf
          MYSQL_DATABASE: currencies
          MYSQL_USER: sammy
          MYSQL_PASSWORD: asdf
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          cd back
          npm install

      - name: Wait for MySQL to be ready
        run: |
          while ! mysqladmin ping -h"127.0.0.1" --silent; do
            sleep 1
          done

      - name: Run tests
        env:
          DB_HOST: 127.0.0.1
          DB_USER: sammy
          DB_PASSWORD: asdf
          DB_NAME: currencies
        run: |
          cd back
          npm test

  # frontend-tests:
  #   runs-on: self-hosted
  #   name: Run Frontend Tests
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '22'

  #     - name: Install dependencies
  #       run: |
  #         cd front
  #         npm install

  #     - name: Run tests
  #       run: |
  #         cd front
  #         npm test

  deploy:
    runs-on: ubuntu-24.01
    needs: [
      backend-tests,
      # frontend-tests
      ]

    name: Deploy Application
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Backend
        run: |
          ssh root@134.209.252.76 "cd /var/www/currency/back && git pull && npm install && npm run build && pm2 restart back"

      - name: Deploy Frontend
        run: |
          ssh root@134.209.252.76 "cd /var/www/currency/front && git pull && npm install && npm run build && pm2 restart front"

      - name: Rollback on Failure
        if: failure()
        run: |
          ssh root@134.209.252.76 "cd /var/www/currency/back && git reset --hard HEAD~1 && pm2 restart back"
          ssh root@134.209.252.76 "cd /var/www/currency/front && git reset --hard HEAD~1 && pm2 restart front"
