name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  backend-tests:
    runs-on: self-hosted
    name: Run Backend Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          cd back
          npm install

      # - name: Check MySQL Connection
      #   run: |
      #     mysql -usammy -pasdf
      #     exit

      - name: Run tests
        env:
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}          # Add this variable in your github repository > Settings > Variables and Secrets > Add Secret
          DATABASE_PORT: 3306               # MySQL's default port
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}       # Add this variable in your github repository > Settings > Variables and Secrets > Add Secret
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}  # Add this variable in your github repository > Settings > Variables and Secrets > Add Secret
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}       # Add this variable in your github repository > Settings > Variables and Secrets > Add Secret
        run: |
          cd back
          npm install mysql --save
          npm run test


  # frontend-tests:
  #   runs-on: self-hosted
  #   name: Run Frontend Tests
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '22'

  #     - name: Install dependencies
  #       run: |
  #         cd front
  #         npm install

  #     - name: Run tests
  #       run: |
  #         cd front
  #         npm test

  deploy:
    runs-on: self-hosted
    needs: [
      backend-tests,
      # frontend-tests
      ]
    name: Deploy Application
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up SSH
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SSH_HOST }} # Add this variable in your github repository > Settings > Variables and Secrets > Add Secret
          username: ${{ secrets.SSH_USERNAME }} # Add this variable in your github repository > Settings > Variables and Secrets > Add Secret
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Add only the key string without "-----BEGIN OPENSSH PRIVATE KEY-----" and "-----END OPENSSH PRIVATE KEY-----"
          script: |
            cd /var/www/currency/back
            git pull
            npm install
            npm run build
            pm2 restart back
            cd /var/www/currency/front
            git pull
            npm install
            npm run build
            pm2 restart front
      - name: Rollback on Failure
        if: failure()
        run: |
          ssh root@134.209.252.76 "cd /var/www/currency/back && git reset --hard HEAD~1 && pm2 restart back"
          ssh root@134.209.252.76 "cd /var/www/currency/front && git reset --hard HEAD~1 && pm2 restart front"

