name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  backend-tests:
    runs-on: ubuntu-24.01
    name: Run Backend Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '28.18.0'

      - name: Install dependencies
        run: |
          cd back
          npm install

      - name: Run tests
        run: |
          cd back
          npm test

  frontend-tests:
    runs-on: ubuntu-24.01
    name: Run Frontend Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '28.18.0'

      - name: Install dependencies
        run: |
          cd front
          npm install

      - name: Run tests
        run: |
          cd front
          npm test

  deploy:
    runs-on: ubuntu-24.01
    needs: [backend-tests, frontend-tests]
    name: Deploy Application
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Backend
        run: |
          ssh user@your-server "cd /path/to/back && git pull && npm install && npm run build && pm2 restart backend"

      - name: Deploy Frontend
        run: |
          ssh user@your-server "cd /path/to/front && git pull && npm install && npm run build && pm2 restart frontend"

      - name: Rollback on Failure
        if: failure()
        run: |
          ssh user@your-server "cd /path/to/back && git reset --hard HEAD~1 && pm2 restart backend"
          ssh user@your-server "cd /path/to/front && git reset --hard HEAD~1 && pm2 restart frontend"
